name: tus_client
description: A tus client for dart allowing resumable uploads using the tus protocol.
version: 2.0.0
homepage: https://github.com/jjmutumi/tus_client

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cross_file: ^0.3.1+4
  http: ^1.2.2
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.3
  build_runner: ^2.4.13
